title: "nathan wentworth ✨"
email: me@nathanwentworth.co
description: "Unity C# game programmer, Javascript web developer"
baseurl: ""
url: "https://nathanwentworth.co"
twitter_username: nathanwentworth
github_username: nathanwentworth
facebook_username: nthnww
permalink: /:collection/:title/
author: "Nathan Wentworth"

links:
  'about': '/about/'
  'twitter': 'https://twitter.com/nathanwentworth'
  'github': 'https://github.com/nathanwentworth'
  'itch.io': 'https://nathanwentworth.itch.io'

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      author: "Nathan Wentworth"
  - scope:
      path: ""
      type: posts
    values:
      layout: project
      hide_date: true
      hide_tags: true
      author: "Nathan Wentworth"
  - scope:
      path: "assets/img/photos"
    values:
      photo: true

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed