# Notes!
# Images on home page should be 420x315

title: "nathan wentworth ✨"
email: me@nathanwentworth.co
description: "programmer and rhythm game fan"
full_description: |
  hello~! welcome to my ~website~

  I like [programming](/projects/), [fun music](https://soundcloud.com/nathanwentworth/sets/fav), video games, animation, [movies](https://letterboxd.com/nathanwentworth/), and [taking photos](https://www.flickr.com/photos/nathanwentworth/)! I love picking up new hobbies every few months, maybe I'll post about some of them in my [blog](/posts/)?? I love sharing things I'm into, which you can find in my [recommendations](/recommendations/) section!

  Feel free to [email me](ma&#105;lto&#58;me&#64;na%74h%&#54;1&#110;&#37;77en%74w&#111;rt&#104;&#46;c&#111;) or talk to me on [twitter](https://twitter.com/nathanwentworth)/[mastodon](https://mastodon.social/@nathanwentworth)! Follow updates on this site with RSS: [posts](/posts-feed.xml) & [recommendations](/recommendations-feed.xml).

site_info: This website is hosted on a [Digital Ocean](https://m.do.co/c/24af6a0d4c4a) droplet running Ubuntu 16 and nginx. [Let's Encrypt](https://letsencrypt.org/) is providing the SSL Cert, and my CMS/site generator is [Jekyll](http://jekyllrb.com/). Feel free to check out this site's source code on [Github](https://github.com/nathanwentworth/nathanwentworth).
baseurl: ""
url: "https://nathanwentworth.co"
twitter_username: nathanwentworth
github_username: nathanwentworth
permalink: /:collection/:title/
author: "Nathan Wentworth"

data_dir: data
auto_ids: true

kaomoji: [
  '(〃￣ω￣〃) ゞ',
  '♪（ｖ＾＿＾）ｖ',
  '( ・ω・)',
  '(´；ω；｀)',
  '\（￣へ￣）/',
  '(◕‿◕✿)'
]

links:
  'projects': '/projects'
  'posts': '/posts'

collections:
  projects:
    output: true
  blog:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      collection: projects
      layout: project
      author: "Nathan Wentworth"
      permalink: /:collection/:title/
  - scope:
      path: ""
      type: blog
    values:
      collection: blog
      layout: project
      author: "Nathan Wentworth"
      permalink: /posts/:title/
  - scope:
      path: ""
      type: posts
    values:
      collection: posts
      layout: project
      author: "Nathan Wentworth"
      img_path: /assets/img/project/:title/
  - scope:
      path: "assets/img/photos"
    values:
      photo: true

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  # style: compressed
  style: expanded