# Notes!
# Images on home page should be 420x315

title: "nathan wentworth ✨"
email: me@nathanwentworth.co
description: "Unity C# game programmer, Javascript web developer"
full_description: |
  Hi! I'm nathan wentworth, I make [video games](/projects/#t:game) and [websites](/projects/#t:web). I like using vanilla/ES6 [JavaScript](/projects/#t:javascript), [Unity C#](/projects/#t:unity), and [Python](/projects/#t:python). Recently I've been into making CLI tools and server-side web apps.

  I'm interested in design, open source software, minimalism, fashion, and the intersection of technology and humanity. I like [fun music](https://soundcloud.com/nathanwentworth/sets/fav), video games, and [taking photos](/photos).

  Currently working freelance for [FableVision Studios](http://www.fablevisionstudios.com/).

  Feel free to [email me](ma&#105;lto&#58;me&#64;na%74h%&#54;1&#110;&#37;77en%74w&#111;rt&#104;&#46;c&#111;) or talk to me on [twitter](https://twitter.com/nathanwentworth)!

site_info: This website is hosted on a [Digital Ocean](https://m.do.co/c/24af6a0d4c4a) droplet running Ubuntu 16 and nginx. [Let's Encrypt](https://letsencrypt.org/) is providing the SSL Cert, and my CMS/site generator is [Jekyll](http://jekyllrb.com/). Feel free to check out this site's source code on [Github](https://github.com/nathanwentworth/nathanwentworth).
baseurl: ""
url: "https://nathanwentworth.co"
twitter_username: nathanwentworth
github_username: nathanwentworth
permalink: /:collection/:title/
author: "Nathan Wentworth"

links:
  'projects': '/projects'
  'posts': '/posts'
  'pages': '/pages'

elsewhere:
  'twitter': 'https://twitter.com/nathanwentworth'
  'mastodon': 'https://mastodon.social/@nathanwentworth'
  'photos': '/photos'
  'sites i like': '/sites-i-like'
  'wishlist': '/wishlist'
  'anime list': 'https://anilist.co/user/nathan/'
  'setup': '/setup'
  'bandcamp collection': 'https://bandcamp.com/nathanwentworth'
  'pinboard': 'https://pinboard.in/u:nathanwentworth'
  'tumblr': 'https://nathanwentworth.tumblr.com/'
  'github': 'https://github.com/nathanwentworth'
  'itch.io': 'https://nathanwentworth.itch.io/'

collections:
  projects:
    output: true
  ppages:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      collection: projects
      layout: project
      author: "Nathan Wentworth"
      permalink: /:collection/:title/
  - scope:
      path: ""
      type: ppages
    values:
      collection: ppages
      layout: project
      author: "Nathan Wentworth"
      permalink: /:title/
  - scope:
      path: ""
      type: posts
    values:
      collection: posts
      layout: project
      hide_aside: true
      author: "Nathan Wentworth"
      img_path: /assets/img/project/:title/
  - scope:
      path: "assets/img/photos"
    values:
      photo: true
  - scope:
      path: "assets/img/photos-sm"
    values:
      photo: true

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  # style: compressed
  style: expanded