title: nathan wentworth
email: me@nathanwentworth.co
description: > # this means to ignore newlines until "baseurl:"
  nathan wentworth - web + game dev
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nathanwentworth.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nathanwentworth
github_username: nathanwentworth
facebook_username: nthnww

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed