title: "nathan wentworth ✨"
email: me@nathanwentworth.co
description: "Unity C# game programmer, Javascript web developer"
baseurl: ""
url: "https://nathanwentworth.co"
twitter_username: nathanwentworth
github_username: nathanwentworth
facebook_username: nthnww
permalink: /:collection/:title/
author: "Nathan Wentworth"

links:
  'twitter': 'https://twitter.com/nathanwentworth'
  'github': 'https://github.com/nathanwentworth'
  'itch.io': 'https://nathanwentworth.itch.io'

elsewhere:
  'email': 'ma&#105;lto&#58;me&#64;na%74h%&#54;1&#110;&#37;77en%74w&#111;rt&#104;&#46;c&#111;'
  'twitter': 'https://twitter.com/nathanwentworth'
  'tumblr': 'https://nathanwentworth.tumblr.com/'
  'github': 'https://github.com/nathanwentworth'
  'instagram': 'https://www.instagram.com/nathanwentworth/'
  'itch.io': 'https://nathanwentworth.itch.io/'

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      author: "Nathan Wentworth"
      permalink: /:collection/:title/
  - scope:
      path: ""
      type: posts
    values:
      layout: project
      hide_date: true
      hide_tags: true
      author: "Nathan Wentworth"
  - scope:
      path: "assets/img/photos"
    values:
      photo: true

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed