title: nathan wentworth
email: me@nathanwentworth.co
description: "Unity C# game programmer, Javascript web developer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nathanwentworth.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nathanwentworth
github_username: nathanwentworth
facebook_username: nthnww
permalink: /project/:title/

links:
  'about': '/about/'
  'twitter': 'https://twitter.com/nathanwentworth'
  'github': 'https://github.com/nathanwentworth'
  'itch.io': 'https://nathanwentworth.itch.io'

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: project
  - scope:
      path: "assets/img/photos"
    values:
      photo: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed