title: "nathan wentworth ✨"
email: me@nathanwentworth.co
description: "Unity C# game programmer, Javascript web developer"
full_description: |
  Hi! I'm nathan wentworth, I make [video games](/games) and [websites](/web). I used to [take photos](https://www.flickr.com/photos/nathanwentworth). I like using vanilla/ES6 JavaScript, Unity C#, and Python. Recently I've been into making CLI tools and server-side web apps.

  I'm interested in design, open source software, minimalism, fashion, and the intersection of technology and humanity.

  Currently working freelance for [FableVision Studios](http://www.fablevisionstudios.com/).

  Feel free to talk to me on [twitter](https://twitter.com/nathanwentworth)!
baseurl: ""
url: "https://nathanwentworth.co"
twitter_username: nathanwentworth
github_username: nathanwentworth
facebook_username: nthnww
permalink: /:collection/:title/
author: "Nathan Wentworth"

links:
  'twitter': 'https://twitter.com/nathanwentworth'
  'github': 'https://github.com/nathanwentworth'
  'itch.io': 'https://nathanwentworth.itch.io'

elsewhere:
  'email': 'ma&#105;lto&#58;me&#64;na%74h%&#54;1&#110;&#37;77en%74w&#111;rt&#104;&#46;c&#111;'
  'twitter': 'https://twitter.com/nathanwentworth'
  'tumblr': 'https://nathanwentworth.tumblr.com/'
  'github': 'https://github.com/nathanwentworth'
  'itch.io': 'https://nathanwentworth.itch.io/'

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      author: "Nathan Wentworth"
      permalink: /:collection/:title/
  - scope:
      path: ""
      type: posts
    values:
      layout: project
      hide_date: true
      hide_tags: true
      author: "Nathan Wentworth"
  - scope:
      path: "assets/img/photos"
    values:
      photo: true

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed