let assets = [
  { url: 'Chiikawa/Clothes/Accessory1.PNG' },
  { url: 'Chiikawa/Clothes/Accessory10.PNG' },
  { url: 'Chiikawa/Clothes/Accessory2.PNG' },
  { url: 'Chiikawa/Clothes/Accessory3.PNG' },
  { url: 'Chiikawa/Clothes/Accessory4.PNG' },
  { url: 'Chiikawa/Clothes/Accessory5.PNG' },
  { url: 'Chiikawa/Clothes/Accessory6.PNG' },
  { url: 'Chiikawa/Clothes/Accessory7.PNG' },
  { url: 'Chiikawa/Clothes/Accessory8.PNG' },
  { url: 'Chiikawa/Clothes/Accessory9.PNG' },
  { url: 'Chiikawa/Clothes/Face1.PNG' },
  { url: 'Chiikawa/Clothes/Face2.PNG' },
  { url: 'Chiikawa/Clothes/Face3.PNG' },
  { url: 'Chiikawa/Clothes/Face4.PNG' },
  { url: 'Chiikawa/Clothes/Face5.PNG' },
  { url: 'Chiikawa/Clothes/Pants1.PNG' },
  { url: 'Chiikawa/Clothes/Pants10.PNG' },
  { url: 'Chiikawa/Clothes/Pants2.PNG' },
  { url: 'Chiikawa/Clothes/Pants3.PNG' },
  { url: 'Chiikawa/Clothes/Pants4.PNG' },
  { url: 'Chiikawa/Clothes/Pants5.PNG' },
  { url: 'Chiikawa/Clothes/Pants6.PNG' },
  { url: 'Chiikawa/Clothes/Pants7.PNG' },
  { url: 'Chiikawa/Clothes/Pants8.PNG' },
  { url: 'Chiikawa/Clothes/Pants9.PNG' },
  { url: 'Chiikawa/Clothes/Shirt1.PNG' },
  { url: 'Chiikawa/Clothes/Shirt10.PNG' },
  { url: 'Chiikawa/Clothes/Shirt2.PNG' },
  { url: 'Chiikawa/Clothes/Shirt3.PNG' },
  { url: 'Chiikawa/Clothes/Shirt4.PNG' },
  { url: 'Chiikawa/Clothes/Shirt5.PNG' },
  { url: 'Chiikawa/Clothes/Shirt6.PNG' },
  { url: 'Chiikawa/Clothes/Shirt7.PNG' },
  { url: 'Chiikawa/Clothes/Shirt8.PNG' },
  { url: 'Chiikawa/Clothes/Shirt9.PNG' },
  { url: 'Chiikawa/Layer 1.PNG' },
  { url: 'Chiikawa/Layer 2.PNG' },
  { url: 'Chiikawa/Layer 3.PNG' },
  { url: 'Furuhonya/Clothes/Accessory1.PNG' },
  { url: 'Furuhonya/Clothes/Accessory10.PNG' },
  { url: 'Furuhonya/Clothes/Accessory2.PNG' },
  { url: 'Furuhonya/Clothes/Accessory3.PNG' },
  { url: 'Furuhonya/Clothes/Accessory4.PNG' },
  { url: 'Furuhonya/Clothes/Accessory5.PNG' },
  { url: 'Furuhonya/Clothes/Accessory6.PNG' },
  { url: 'Furuhonya/Clothes/Accessory7.PNG' },
  { url: 'Furuhonya/Clothes/Accessory8.PNG' },
  { url: 'Furuhonya/Clothes/Accessory9.PNG' },
  { url: 'Furuhonya/Clothes/Face1.PNG' },
  { url: 'Furuhonya/Clothes/Face2.PNG' },
  { url: 'Furuhonya/Clothes/Face3.PNG' },
  { url: 'Furuhonya/Clothes/Face4.PNG' },
  { url: 'Furuhonya/Clothes/Face5.PNG' },
  { url: 'Furuhonya/Clothes/Pants1.PNG' },
  { url: 'Furuhonya/Clothes/Pants10.PNG' },
  { url: 'Furuhonya/Clothes/Pants2.PNG' },
  { url: 'Furuhonya/Clothes/Pants3.PNG' },
  { url: 'Furuhonya/Clothes/Pants4.PNG' },
  { url: 'Furuhonya/Clothes/Pants5.PNG' },
  { url: 'Furuhonya/Clothes/Pants6.PNG' },
  { url: 'Furuhonya/Clothes/Pants7.PNG' },
  { url: 'Furuhonya/Clothes/Pants8.PNG' },
  { url: 'Furuhonya/Clothes/Pants9.PNG' },
  { url: 'Furuhonya/Clothes/Shirt1.PNG' },
  { url: 'Furuhonya/Clothes/Shirt10.PNG' },
  { url: 'Furuhonya/Clothes/Shirt2.PNG' },
  { url: 'Furuhonya/Clothes/Shirt3.PNG' },
  { url: 'Furuhonya/Clothes/Shirt4.PNG' },
  { url: 'Furuhonya/Clothes/Shirt5.PNG' },
  { url: 'Furuhonya/Clothes/Shirt6.PNG' },
  { url: 'Furuhonya/Clothes/Shirt7.PNG' },
  { url: 'Furuhonya/Clothes/Shirt8.PNG' },
  { url: 'Furuhonya/Clothes/Shirt9.PNG' },
  { url: 'Furuhonya/Layer 16.PNG' },
  { url: 'Furuhonya/Layer 17.PNG' },
  { url: 'Furuhonya/Layer 3.PNG' },
  { url: 'Hachiware/Clothes/Accessory1.PNG' },
  { url: 'Hachiware/Clothes/Accessory10.PNG' },
  { url: 'Hachiware/Clothes/Accessory2.PNG' },
  { url: 'Hachiware/Clothes/Accessory3.PNG' },
  { url: 'Hachiware/Clothes/Accessory4.PNG' },
  { url: 'Hachiware/Clothes/Accessory5.PNG' },
  { url: 'Hachiware/Clothes/Accessory6.PNG' },
  { url: 'Hachiware/Clothes/Accessory7.PNG' },
  { url: 'Hachiware/Clothes/Accessory8.PNG' },
  { url: 'Hachiware/Clothes/Accessory9.PNG' },
  { url: 'Hachiware/Clothes/Face1.PNG' },
  { url: 'Hachiware/Clothes/Face2.PNG' },
  { url: 'Hachiware/Clothes/Face3.PNG' },
  { url: 'Hachiware/Clothes/Face4.PNG' },
  { url: 'Hachiware/Clothes/Face5.PNG' },
  { url: 'Hachiware/Clothes/Pants1.PNG' },
  { url: 'Hachiware/Clothes/Pants10.PNG' },
  { url: 'Hachiware/Clothes/Pants2.PNG' },
  { url: 'Hachiware/Clothes/Pants3.PNG' },
  { url: 'Hachiware/Clothes/Pants4.PNG' },
  { url: 'Hachiware/Clothes/Pants5.PNG' },
  { url: 'Hachiware/Clothes/Pants6.PNG' },
  { url: 'Hachiware/Clothes/Pants7.PNG' },
  { url: 'Hachiware/Clothes/Pants8.PNG' },
  { url: 'Hachiware/Clothes/Pants9.PNG' },
  { url: 'Hachiware/Clothes/Shirt1.PNG' },
  { url: 'Hachiware/Clothes/Shirt10.PNG' },
  { url: 'Hachiware/Clothes/Shirt2.PNG' },
  { url: 'Hachiware/Clothes/Shirt3.PNG' },
  { url: 'Hachiware/Clothes/Shirt4.PNG' },
  { url: 'Hachiware/Clothes/Shirt5.PNG' },
  { url: 'Hachiware/Clothes/Shirt6.PNG' },
  { url: 'Hachiware/Clothes/Shirt7.PNG' },
  { url: 'Hachiware/Clothes/Shirt8.PNG' },
  { url: 'Hachiware/Clothes/Shirt9.PNG' },
  { url: 'Hachiware/Layer 4.PNG' },
  { url: 'Hachiware/Layer 5.PNG' },
  { url: 'Hachiware/Layer 6.PNG' },
  { url: 'Kurimanju/Clothes/Accessory1.PNG' },
  { url: 'Kurimanju/Clothes/Accessory2.PNG' },
  { url: 'Kurimanju/Clothes/Accessory3.PNG' },
  { url: 'Kurimanju/Clothes/Accessory4.PNG' },
  { url: 'Kurimanju/Clothes/Accessory5.PNG' },
  { url: 'Kurimanju/Clothes/Accessory6.PNG' },
  { url: 'Kurimanju/Clothes/Accessory7.PNG' },
  { url: 'Kurimanju/Clothes/Accessory8.PNG' },
  { url: 'Kurimanju/Clothes/Face1.PNG' },
  { url: 'Kurimanju/Clothes/Face2.PNG' },
  { url: 'Kurimanju/Clothes/Face3.PNG' },
  { url: 'Kurimanju/Clothes/Face4.PNG' },
  { url: 'Kurimanju/Clothes/Face5.PNG' },
  { url: 'Kurimanju/Clothes/Layer 20.PNG' },
  { url: 'Kurimanju/Clothes/Pants1.PNG' },
  { url: 'Kurimanju/Clothes/Pants10.PNG' },
  { url: 'Kurimanju/Clothes/Pants2.PNG' },
  { url: 'Kurimanju/Clothes/Pants3.PNG' },
  { url: 'Kurimanju/Clothes/Pants4.PNG' },
  { url: 'Kurimanju/Clothes/Pants5.PNG' },
  { url: 'Kurimanju/Clothes/Pants6.PNG' },
  { url: 'Kurimanju/Clothes/Pants7.PNG' },
  { url: 'Kurimanju/Clothes/Pants8.PNG' },
  { url: 'Kurimanju/Clothes/Pants9.PNG' },
  { url: 'Kurimanju/Clothes/Shirt1.PNG' },
  { url: 'Kurimanju/Clothes/Shirt10.PNG' },
  { url: 'Kurimanju/Clothes/Shirt2.PNG' },
  { url: 'Kurimanju/Clothes/Shirt3.PNG' },
  { url: 'Kurimanju/Clothes/Shirt4.PNG' },
  { url: 'Kurimanju/Clothes/Shirt5.PNG' },
  { url: 'Kurimanju/Clothes/Shirt6.PNG' },
  { url: 'Kurimanju/Clothes/Shirt7.PNG' },
  { url: 'Kurimanju/Clothes/Shirt8.PNG' },
  { url: 'Kurimanju/Clothes/Shirt9.PNG' },
  { url: 'Kurimanju/Layer 10.PNG' },
  { url: 'Kurimanju/Layer 3.PNG' },
  { url: 'Kurimanju/Layer 9.PNG' },
  { url: 'Layer 21.PNG' },
  { url: 'Layer 23.PNG' },
  { url: 'Layer 24.PNG' },
  { url: 'Layer 25.PNG' },
  { url: 'Layer 26.PNG' },
  { url: 'Layer 27.PNG' },
  { url: 'Mockup/avatar-template.PNG' },
  { url: 'Mockup/Ui mockup.PNG' },
  { url: 'Momonga/Clothes/Accessory1.PNG' },
  { url: 'Momonga/Clothes/Accessory10.PNG' },
  { url: 'Momonga/Clothes/Accessory2.PNG' },
  { url: 'Momonga/Clothes/Accessory3.PNG' },
  { url: 'Momonga/Clothes/Accessory4.PNG' },
  { url: 'Momonga/Clothes/Accessory5.PNG' },
  { url: 'Momonga/Clothes/Accessory6.PNG' },
  { url: 'Momonga/Clothes/Accessory7.PNG' },
  { url: 'Momonga/Clothes/Accessory8.PNG' },
  { url: 'Momonga/Clothes/Accessory9.PNG' },
  { url: 'Momonga/Clothes/Face1.PNG' },
  { url: 'Momonga/Clothes/Face2.PNG' },
  { url: 'Momonga/Clothes/Face3.PNG' },
  { url: 'Momonga/Clothes/Face4.PNG' },
  { url: 'Momonga/Clothes/Face5.PNG' },
  { url: 'Momonga/Clothes/Pants1.PNG' },
  { url: 'Momonga/Clothes/Pants10.PNG' },
  { url: 'Momonga/Clothes/Pants2.PNG' },
  { url: 'Momonga/Clothes/Pants3.PNG' },
  { url: 'Momonga/Clothes/Pants4.PNG' },
  { url: 'Momonga/Clothes/Pants5.PNG' },
  { url: 'Momonga/Clothes/Pants6.PNG' },
  { url: 'Momonga/Clothes/Pants7.PNG' },
  { url: 'Momonga/Clothes/Pants8.PNG' },
  { url: 'Momonga/Clothes/Pants9.PNG' },
  { url: 'Momonga/Clothes/Shirt1.PNG' },
  { url: 'Momonga/Clothes/Shirt10.PNG' },
  { url: 'Momonga/Clothes/Shirt2.PNG' },
  { url: 'Momonga/Clothes/Shirt3.PNG' },
  { url: 'Momonga/Clothes/Shirt4.PNG' },
  { url: 'Momonga/Clothes/Shirt5.PNG' },
  { url: 'Momonga/Clothes/Shirt6.PNG' },
  { url: 'Momonga/Clothes/Shirt7.PNG' },
  { url: 'Momonga/Clothes/Shirt8.PNG' },
  { url: 'Momonga/Clothes/Shirt9.PNG' },
  { url: 'Momonga/Layer 11.PNG' },
  { url: 'Momonga/Layer 12.PNG' },
  { url: 'Momonga/Layer 3.PNG' },
  { url: 'Names/Chiikawa.PNG' },
  { url: 'Names/Furuhonya.PNG' },
  { url: 'Names/Hachiware.PNG' },
  { url: 'Names/Kurimanju.PNG' },
  { url: 'Names/Momonga.PNG' },
  { url: 'Names/Rakko.PNG' },
  { url: 'Names/Shisa.PNG' },
  { url: 'Names/Usagi.PNG' },
  { url: 'Paper.PNG' },
  { url: 'Rakko/Clothes/Accessory1.PNG' },
  { url: 'Rakko/Clothes/Accessory10.PNG' },
  { url: 'Rakko/Clothes/Accessory2.PNG' },
  { url: 'Rakko/Clothes/Accessory3.PNG' },
  { url: 'Rakko/Clothes/Accessory4.PNG' },
  { url: 'Rakko/Clothes/Accessory5.PNG' },
  { url: 'Rakko/Clothes/Accessory6.PNG' },
  { url: 'Rakko/Clothes/Accessory7.PNG' },
  { url: 'Rakko/Clothes/Accessory8.PNG' },
  { url: 'Rakko/Clothes/Accessory9.PNG' },
  { url: 'Rakko/Clothes/Face1.PNG' },
  { url: 'Rakko/Clothes/Face2.PNG' },
  { url: 'Rakko/Clothes/Face3.PNG' },
  { url: 'Rakko/Clothes/Face4.PNG' },
  { url: 'Rakko/Clothes/Face5.PNG' },
  { url: 'Rakko/Clothes/Pants1.PNG' },
  { url: 'Rakko/Clothes/Pants10.PNG' },
  { url: 'Rakko/Clothes/Pants2.PNG' },
  { url: 'Rakko/Clothes/Pants3.PNG' },
  { url: 'Rakko/Clothes/Pants4.PNG' },
  { url: 'Rakko/Clothes/Pants5.PNG' },
  { url: 'Rakko/Clothes/Pants6.PNG' },
  { url: 'Rakko/Clothes/Pants7.PNG' },
  { url: 'Rakko/Clothes/Pants8.PNG' },
  { url: 'Rakko/Clothes/Pants9.PNG' },
  { url: 'Rakko/Clothes/Shirt1.PNG' },
  { url: 'Rakko/Clothes/Shirt10.PNG' },
  { url: 'Rakko/Clothes/Shirt2.PNG' },
  { url: 'Rakko/Clothes/Shirt3.PNG' },
  { url: 'Rakko/Clothes/Shirt4.PNG' },
  { url: 'Rakko/Clothes/Shirt5.PNG' },
  { url: 'Rakko/Clothes/Shirt6.PNG' },
  { url: 'Rakko/Clothes/Shirt7.PNG' },
  { url: 'Rakko/Clothes/Shirt8.PNG' },
  { url: 'Rakko/Clothes/Shirt9.PNG' },
  { url: 'Rakko/Layer 18.PNG' },
  { url: 'Rakko/Layer 19.PNG' },
  { url: 'Rakko/Layer 3.PNG' },
  { url: 'Shisa/Clothes/Accessory1.PNG' },
  { url: 'Shisa/Clothes/Accessory10.PNG' },
  { url: 'Shisa/Clothes/Accessory2.PNG' },
  { url: 'Shisa/Clothes/Accessory3.PNG' },
  { url: 'Shisa/Clothes/Accessory4.PNG' },
  { url: 'Shisa/Clothes/Accessory5.PNG' },
  { url: 'Shisa/Clothes/Accessory6.PNG' },
  { url: 'Shisa/Clothes/Accessory7.PNG' },
  { url: 'Shisa/Clothes/Accessory8.PNG' },
  { url: 'Shisa/Clothes/Accessory9.PNG' },
  { url: 'Shisa/Clothes/Face1.PNG' },
  { url: 'Shisa/Clothes/Face2.PNG' },
  { url: 'Shisa/Clothes/Face3.PNG' },
  { url: 'Shisa/Clothes/Face4.PNG' },
  { url: 'Shisa/Clothes/Face5.PNG' },
  { url: 'Shisa/Clothes/Pants1.PNG' },
  { url: 'Shisa/Clothes/Pants10.PNG' },
  { url: 'Shisa/Clothes/Pants2.PNG' },
  { url: 'Shisa/Clothes/Pants3.PNG' },
  { url: 'Shisa/Clothes/Pants4.PNG' },
  { url: 'Shisa/Clothes/Pants5.PNG' },
  { url: 'Shisa/Clothes/Pants6.PNG' },
  { url: 'Shisa/Clothes/Pants7.PNG' },
  { url: 'Shisa/Clothes/Pants8.PNG' },
  { url: 'Shisa/Clothes/Pants9.PNG' },
  { url: 'Shisa/Clothes/Shirt1.PNG' },
  { url: 'Shisa/Clothes/Shirt10.PNG' },
  { url: 'Shisa/Clothes/Shirt2.PNG' },
  { url: 'Shisa/Clothes/Shirt3.PNG' },
  { url: 'Shisa/Clothes/Shirt4.PNG' },
  { url: 'Shisa/Clothes/Shirt5.PNG' },
  { url: 'Shisa/Clothes/Shirt6.PNG' },
  { url: 'Shisa/Clothes/Shirt7.PNG' },
  { url: 'Shisa/Clothes/Shirt8.PNG' },
  { url: 'Shisa/Clothes/Shirt9.PNG' },
  { url: 'Shisa/Layer 14.PNG' },
  { url: 'Shisa/Layer 15.PNG' },
  { url: 'Shisa/Layer 3.PNG' },
  { url: 'Usagi/Clothes/Accessory1.PNG' },
  { url: 'Usagi/Clothes/Accessory10.PNG' },
  { url: 'Usagi/Clothes/Accessory2.PNG' },
  { url: 'Usagi/Clothes/Accessory3.PNG' },
  { url: 'Usagi/Clothes/Accessory4.PNG' },
  { url: 'Usagi/Clothes/Accessory5.PNG' },
  { url: 'Usagi/Clothes/Accessory6.PNG' },
  { url: 'Usagi/Clothes/Accessory7.PNG' },
  { url: 'Usagi/Clothes/Accessory8.PNG' },
  { url: 'Usagi/Clothes/Accessory9.PNG' },
  { url: 'Usagi/Clothes/Face1.PNG' },
  { url: 'Usagi/Clothes/Face2.PNG' },
  { url: 'Usagi/Clothes/Face3.PNG' },
  { url: 'Usagi/Clothes/Face4.PNG' },
  { url: 'Usagi/Clothes/Face5.PNG' },
  { url: 'Usagi/Clothes/Pants1.PNG' },
  { url: 'Usagi/Clothes/Pants10.PNG' },
  { url: 'Usagi/Clothes/Pants2.PNG' },
  { url: 'Usagi/Clothes/Pants3.PNG' },
  { url: 'Usagi/Clothes/Pants4.PNG' },
  { url: 'Usagi/Clothes/Pants5.PNG' },
  { url: 'Usagi/Clothes/Pants6.PNG' },
  { url: 'Usagi/Clothes/Pants7.PNG' },
  { url: 'Usagi/Clothes/Pants8.PNG' },
  { url: 'Usagi/Clothes/Pants9.PNG' },
  { url: 'Usagi/Clothes/Shirt1.PNG' },
  { url: 'Usagi/Clothes/Shirt10.PNG' },
  { url: 'Usagi/Clothes/Shirt2.PNG' },
  { url: 'Usagi/Clothes/Shirt3.PNG' },
  { url: 'Usagi/Clothes/Shirt4.PNG' },
  { url: 'Usagi/Clothes/Shirt5.PNG' },
  { url: 'Usagi/Clothes/Shirt6.PNG' },
  { url: 'Usagi/Clothes/Shirt7.PNG' },
  { url: 'Usagi/Clothes/Shirt8.PNG' },
  { url: 'Usagi/Clothes/Shirt9.PNG' },
  { url: 'Usagi/Layer 6.PNG' },
  { url: 'Usagi/Layer 7.PNG' },
  { url: 'Usagi/Layer 8.PNG' },
  { url: 'Layer 21.PNG' },
  { url: 'Layer 23.PNG' },
  { url: 'Layer 24.PNG' },
  { url: 'Layer 25.PNG' },
  { url: 'Layer 26.PNG' },
  { url: 'Layer 27.PNG' },
  { url: 'Paper.PNG' },
]

let characters = {
  Chiikawa: {
    name: 'Chiikawa',
    base: ['Layer 3', 'Layer 2', 'Layer 1'],
    accessory: 10,
    face: 5,
    pants: 10,
    shirt: 10,
  },
  Hachiware: {
    name: 'Hachiware',
    base: ['Layer 6', 'Layer 5', 'Layer 4'],
    accessory: 10,
    face: 5,
    pants: 10,
    shirt: 10,
  },
  Kurimanju: {
    name: 'Kurimanju',
    base: ['Layer 3', 'Layer 10', 'Layer 9'],
    accessory: 10,
    face: 5,
    pants: 10,
    shirt: 10,
  },
  Usagi: {
    name: 'Usagi',
    base: ['Layer 6', 'Layer 8', 'Layer 7'],
    accessory: 10,
    face: 5,
    pants: 10,
    shirt: 10,
  },
  Shisa: {
    name: 'Shisa',
    base: ['Layer 3', 'Layer 15', 'Layer 14'],
    accessory: 10,
    face: 5,
    pants: 10,
    shirt: 10,
  },
  Rakko: {
    name: 'Rakko',
    base: ['Layer 3', 'Layer 19', 'Layer 18'],
    accessory: 10,
    face: 5,
    pants: 10,
    shirt: 10,
  },
  Momonga: {
    name: 'Momonga',
    base: ['Layer 3', 'Layer 12', 'Layer 11'],
    accessory: 10,
    face: 5,
    pants: 10,
    shirt: 10,
  },
  Furuhonya: {
    name: 'Furuhonya',
    base: ['Layer 3', 'Layer 17', 'Layer 16'],
    accessory: 10,
    face: 5,
    pants: 10,
    shirt: 10,
  },
}

export { assets, characters }
